// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package sampleapp.actions;

import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;
import com.mendix.thirdparty.org.json.JSONObject;
import tcconnector.foundation.TcConnection;
import tcconnector.proxies.TcSession;

public class CallTcActionWithPolicy extends UserAction<java.lang.String>
{
	private final java.lang.String PolicyHeader;
	private final java.lang.String SearchBody;
	private final java.lang.String ServiceName;
	private final java.lang.String ConfigurationName;

	public CallTcActionWithPolicy(
		IContext context,
		java.lang.String _policyHeader,
		java.lang.String _searchBody,
		java.lang.String _serviceName,
		java.lang.String _configurationName
	)
	{
		super(context);
		this.PolicyHeader = _policyHeader;
		this.SearchBody = _searchBody;
		this.ServiceName = _serviceName;
		this.ConfigurationName = _configurationName;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		ILogNode LOGGER = Core.getLogger("CallTeamcenterServiceLogger");

        try {

            JSONObject inputJson = new JSONObject(this.SearchBody);
            JSONObject policyJson = new JSONObject(this.PolicyHeader);

//            ensureUserLoggedIn(getContext(), this.ConfigurationName);

            // Call Teamcenter Service
            JSONObject response = TcConnection.callTeamcenterService(getContext(), this.ServiceName, inputJson, policyJson, this.ConfigurationName);

            return response.toString();
        } catch (Exception e) {
            LOGGER.error("❌ CallTeamcenterService: Response error: " + e.toString());
            return "";
        }
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "CallTcActionWithPolicy";
	}

	// BEGIN EXTRA CODE
	private static void ensureUserLoggedIn(IContext context, String configurationName) throws Exception {
        if (configurationName == null || configurationName.trim().isEmpty()) {
            throw new Exception("Configuration name is missing.");
        }
        ILogNode LOGGER = Core.getLogger("CallTeamcenterServiceLogger");

        try {

            // Retrieve existing session
            TcSession tcSession = tcconnector.proxies.microflows.Microflows.retrieveTcSessionBasedOnConfigName(context, configurationName);

            // Define login service
            String loginServiceName = "Core-2011-06-Session/login";


            JSONObject loginPayload = new JSONObject();
            JSONObject credentials = new JSONObject();
            credentials.put("user", "tcadmin");
            credentials.put("password", "tcadmin");
            credentials.put("locale", "en_US");
            credentials.put("group", "");
            credentials.put("descrimator", "");
            credentials.put("role", "");
            loginPayload.put("credentials", credentials);

            // Call the login service
            JSONObject response = TcConnection.callTeamcenterService(context, loginServiceName, loginPayload, null, configurationName);

            if (response == null || !response.has("serverInfo")) {
                LOGGER.info("❌ Login Response: " + response.toString());
                LOGGER.error("❌ Login failed. Unable to establish a session.");
                return;
            }

            LOGGER.info("✅ Successfully logged in to Teamcenter.");
        } catch (Exception e) {
            LOGGER.error("❌ Login failed. Unable to establish a session.");
        }
    }
	// END EXTRA CODE
}
