// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package tcconnector.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import tcconnector.foundation.TcConnection;
import tcconnector.proxies.ServiceResponse;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Tc Version:
 * Teamcenter 10.1.5
 * 
 * Description:
 * The CallTeamcenterService Java Action is the entry point for calling Teamcenter service operations from a Microflow. This Java Action allows the developer to create a custom mapping between the Teamcenter service operation and the Mendix Domain Model Entities.
 * 
 * Returns:
 * Service response of type TcConnector.ServiceResponse. The returned list of model objects can be retrieved using appropriate association. Partial errors can be retrieved using TcConnector.ResponseData/TcConnector.PartialErrors
 * 
 * For more information on the usage of this Java Action kindly refer to connector documentation.
 */
public class CallTeamcenterService extends UserAction<IMendixObject>
{
	private final java.lang.String ServiceName;
	private final IMendixObject InputArgument;
	/** @deprecated use ResponseObject.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __ResponseObject;
	private final tcconnector.proxies.ServiceResponse ResponseObject;
	private final java.lang.String OperationMapping;
	private final java.lang.String BusinessObjectMappings;
	private final java.lang.String ConfigurationName;

	public CallTeamcenterService(
		IContext context,
		java.lang.String _serviceName,
		IMendixObject _inputArgument,
		IMendixObject _responseObject,
		java.lang.String _operationMapping,
		java.lang.String _businessObjectMappings,
		java.lang.String _configurationName
	)
	{
		super(context);
		this.ServiceName = _serviceName;
		this.InputArgument = _inputArgument;
		this.__ResponseObject = _responseObject;
		this.ResponseObject = _responseObject == null ? null : tcconnector.proxies.ServiceResponse.initialize(getContext(), _responseObject);
		this.OperationMapping = _operationMapping;
		this.BusinessObjectMappings = _businessObjectMappings;
		this.ConfigurationName = _configurationName;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		// TcSession tcSession = null;
		ServiceResponse response = TcConnection.callTeamcenterService(getContext(), ServiceName, InputArgument,
				ResponseObject, OperationMapping, BusinessObjectMappings, ConfigurationName, true);
		return response.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "CallTeamcenterService";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
