// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package tcconnector.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import tcconnector.foundation.TcConnection;
import tcconnector.internal.foundation.Constants;
import tcconnector.proxies.CreateRelationResponse;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * SOA URL:
 * Core-2006-03-DataManagement/createRelations
 * 
 * Description:
 * Creates the specified relation between the input objects (primary and secondary objects). If the primary object has a relation property by the specified relation name, then the secondary object is associated with the primary object through the relation property.
 * 
 * Returns:
 * The created relations. The partial error is returned for any request relation types that are not valid relation type name.
 */
public class CreateRelation extends UserAction<IMendixObject>
{
	/** @deprecated use InputData.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __InputData;
	private final tcconnector.proxies.CreateRelationInput InputData;
	private final java.lang.String BusinessObjectMappings;
	private final java.lang.String ConfigurationName;

	public CreateRelation(
		IContext context,
		IMendixObject _inputData,
		java.lang.String _businessObjectMappings,
		java.lang.String _configurationName
	)
	{
		super(context);
		this.__InputData = _inputData;
		this.InputData = _inputData == null ? null : tcconnector.proxies.CreateRelationInput.initialize(getContext(), _inputData);
		this.BusinessObjectMappings = _businessObjectMappings;
		this.ConfigurationName = _configurationName;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		CreateRelationResponse response = new CreateRelationResponse(getContext());
		response = (CreateRelationResponse) TcConnection.callTeamcenterService(getContext(),
				Constants.OPERATION_CREATERELATIONS, InputData.getMendixObject(), response, SERVICE_OPERATION_MAP,
				BusinessObjectMappings, ConfigurationName, true);
		return response.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "CreateRelation";
	}

	// BEGIN EXTRA CODE

	private static final String SERVICE_OPERATION_MAP = "OperationMapping/Core/2006-03/DataManagement/createRelations.json";
	// END EXTRA CODE
}
