// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package tcconnector.actions;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.thirdparty.org.json.JSONArray;
import com.mendix.thirdparty.org.json.JSONObject;
import com.mendix.webui.CustomJavaAction;
import com.teamcenter.fms.servercache.FSCException;
import com.teamcenter.fms.servercache.proxy.CommonsFSCWholeFileIOImpl;
import tcconnector.foundation.JModelObject;
import tcconnector.foundation.JServiceData;
import tcconnector.foundation.TcConnection;
import tcconnector.foundation.exceptions.NotLoadedExcpetion;
import tcconnector.internal.foundation.Constants;
import tcconnector.internal.foundation.FMSUtils;
import tcconnector.internal.foundation.Messages;
import tcconnector.proxies.FileDocument;
import tcconnector.proxies.Image;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * SOA URL: 
 * Core-2006-03-DataManagement/getProperties
 * Core-2006-03-FileManagement/getFileReadTickets
 * 
 * Downloads all the files associated with the Dataset as TcConnector.Image entity 
 * 
 * Input -
 * - Dataset object having UID
 * 
 * Output -
 * - Action returns True or False in case of success and failure respectively.
 * - Input object's Dataset.Documents association will be updated to point to downloaded files if any.
 * 
 */
public class DownloadImages extends UserAction<java.lang.Boolean>
{
	/** @deprecated use DatasetParameter.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __DatasetParameter;
	private final tcconnector.proxies.Dataset DatasetParameter;
	private final java.lang.String ConfigurationName;

	public DownloadImages(
		IContext context,
		IMendixObject _datasetParameter,
		java.lang.String _configurationName
	)
	{
		super(context);
		this.__DatasetParameter = _datasetParameter;
		this.DatasetParameter = _datasetParameter == null ? null : tcconnector.proxies.Dataset.initialize(getContext(), _datasetParameter);
		this.ConfigurationName = _configurationName;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		boolean areFilesDownloaded = Boolean.FALSE;
		try {
			JSONObject datasetObjWithRefList = retrieveDatasetRefList();
			List<IMendixObject> files = retrieveFileListUIDs(datasetObjWithRefList);

			if (!files.isEmpty()) {
				JSONObject body = generateBodyGetFileReadTickets(files);
				JSONObject getFileReadTicketsResponse = getFileReadTickets(body.toString(), ConfigurationName);

				ArrayList<Image> images = downloadFilesFromFMS(getFileReadTicketsResponse,
						this.DatasetParameter);
				DatasetParameter.setImages(getContext(), images);
				areFilesDownloaded = Boolean.TRUE;
			} else {
				Constants.LOGGER.info(Messages.Dataset.NoFilesAvailableToDownload);
			}
		} catch (Exception e) {
			Constants.LOGGER.error(Messages.Dataset.DownloadFilesError + e.getMessage());
			throw e;
		}
		return areFilesDownloaded;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "DownloadImages";
	}

	// BEGIN EXTRA CODE

	private String checkForNull(String input) {
		return input.length() > 0 ? input : "";
	}

	private ArrayList<String> createSubstitutionsForGetProperties() {
		ArrayList<String> substitutions = new java.util.ArrayList<>();
		substitutions.add(checkForNull(DatasetParameter.getUID(getContext())));
		return substitutions;
	}

	/*
	 * Retrieve ImanFile UID & File name
	 */
	private List<IMendixObject> retrieveFileListUIDs(JSONObject fileListResponse) {
		List<IMendixObject> iMendixObjectList = new ArrayList<>();

		JServiceData object = (JServiceData) fileListResponse;
		List<JModelObject> plainObjects = object.getPlainObjects();

		for (int i = 0; i < plainObjects.size(); i++) {
			JModelObject dataSet = plainObjects.get(i);
			if (dataSet != null && dataSet.getUID().equals(DatasetParameter.getUID(getContext()))) {
				try {
					List<String> uiValues = dataSet.getPropertyValues("ref_list");
					List<JModelObject> dbValues = dataSet.getPropertyValueAsModelObjects("ref_list");
					for (int j = 0; j < dbValues.size(); j++) {
						IMendixObject datasetType = Core.instantiate(getContext(), tcconnector.proxies.Pair.entityName);
						datasetType.setValue(getContext(), "Name", uiValues.get(j));
						datasetType.setValue(getContext(), "Value", dbValues.get(j).getUID());
						iMendixObjectList.add(datasetType);
					}
				} catch (NotLoadedExcpetion e) {
					/*
					 * In catch means there is empty ref_list. This is valid scenario and ignore
					 * this exception
					 */
				}
			}
		}

		return iMendixObjectList;
	}

	private ArrayList<Image> downloadFilesFromFMS(JSONObject getFileReadTicketsResponse,
			tcconnector.proxies.Dataset dataset) throws FSCException, IOException {
		ArrayList<Image> documents = new java.util.ArrayList<>();

		/*
		 * Initialize FMS
		 */
		CommonsFSCWholeFileIOImpl fscFileIOImpl = FMSUtils.initializeFMS(getContext(), ConfigurationName);
		/*
		 * Parse getFileTicketsResponse and get ticket(s) information from that.
		 */

		JSONArray tickets = getFileReadTicketsResponse.getJSONArray("tickets");
		/*
		 * getFileReadTickets returns response having 2 arrays under 'tickets'. First
		 * array would contain ImanFile objects Second array contains list of
		 * corresponding tickets
		 * -------------------------------------------------------------------- {
		 * tickets: [ ["ImanFileObjects"], ["Tickets"] ], serviceData: "IServiceData" }
		 * --------------------------------------------------------------------
		 */
		List<List<String>> imanFileObjectList = new ArrayList<>();
		for (int i = 0; i < tickets.getJSONArray(1).length(); i++) {
			List<String> fileTciketAndNameList = new ArrayList<>();
			JModelObject imanFileObject = (JModelObject) tickets.getJSONArray(0).getJSONObject(i);
			String fileTicket = tickets.getJSONArray(1).getString(i);
			String originalFileName = imanFileObject.getPropertyValueAsString("original_file_name");
			fileTciketAndNameList.add(fileTicket);
			fileTciketAndNameList.add(originalFileName);
			fileTciketAndNameList.add(imanFileObject.getUID());
			imanFileObjectList.add(fileTciketAndNameList);
		}

		if (!imanFileObjectList.isEmpty()) {

			String[] fmsURLs = FMSUtils.retrieveFMSURLs(getContext(), ConfigurationName);
			imanFileObjectList.parallelStream().forEach(s -> {
				try {
					documents.add(downloadFiles(s, fmsURLs, fscFileIOImpl, dataset.getUID(getContext())));
				} catch (Exception e) {
					Constants.LOGGER.error(Messages.Dataset.DownloadFilesError + e.getMessage());
				}
			});
		}
		return documents;
	}

	private Image downloadFiles(List<String> fileTciketAndNameList, String[] fmsURLs,
			CommonsFSCWholeFileIOImpl fscFileIOImpl, String datasetUid) throws Exception {
		String fileTicket = fileTciketAndNameList.get(0);
		String originalFileName = fileTciketAndNameList.get(1);
		String imanFileID = fileTciketAndNameList.get(2);

		/*
		 * Create FileDocument object and stream to get file from FMS
		 */
		IMendixObject imageObject = Core.instantiate(getContext(), tcconnector.proxies.Image.entityName);
		Image image = Image.initialize(getContext(), imageObject);
		image.setName(originalFileName);
		image.setdatasetUID(datasetUid);
		image.setimanFileID(imanFileID);
		ByteArrayOutputStream os = new ByteArrayOutputStream();

		/*
		 * get stream from FMS
		 */
		fscFileIOImpl.download("TCM", fmsURLs, fileTicket, os);
		ByteArrayInputStream is = new ByteArrayInputStream(os.toByteArray());
		Core.storeFileDocumentContent(getContext(), imageObject, is);
		os.close();
		is.close();
		return image;
	}

	/*
	 * get ImanFile UIDs from dataset response
	 */
	private JSONObject generateBodyGetFileReadTickets(List<IMendixObject> refList) {
		JSONObject body = new JSONObject();
		JSONArray filesVec = new JSONArray();
		for (int cnt = 0; cnt < refList.size(); ++cnt) {
			JSONObject file = new JSONObject();
			IMendixObject imanFileObject = refList.get(cnt);
			file.put("uid", imanFileObject.getMember(getContext(), "Value").getValue(getContext()));
			filesVec.put(file);
		}
		body.put("files", filesVec);
		return body;
	}

	private static String createServiceInput(String jsonTemplate, ArrayList<String> substitutions) {
		for (int i = 0; i < substitutions.size(); i++) {
			String replacement = substitutions.get(i);
			String target = "{" + (i + 1) + "}";
			jsonTemplate = jsonTemplate.replace(target, replacement);
		}
		return jsonTemplate;
	}

	/*
	 * Call TC Service and get refList for dataset.
	 */
	private JSONObject retrieveDatasetRefList() throws Exception {
		// Create getProperties ref_list JSON template
		String body = "\r\n" + "{\r\n" + "    \"objects\": [\r\n" + "        \"{1}\"\r\n" + "    ],\r\n"
				+ "    \"attributes\": [\r\n" + "        \"ref_list\",\r\n" + "		\"last_mod_date\" \r\n	]\r\n"
				+ "}\r\n" + "\r\n" + "";

		// substitutions for createDatasets
		ArrayList<String> substitutions = createSubstitutionsForGetProperties();
		body = createServiceInput(body, substitutions);

		return TcConnection.callTeamcenterService(getContext(), Constants.OPERATION_GETPROPERTIES, body,
				new JSONObject(), ConfigurationName);
	}

	/*
	 * Call TC Service and get tickets of ImanFile(s)
	 */
	private JSONObject getFileReadTickets(String getFileReadTicketsJT, String configurationName) throws Exception {
		JSONObject emptyPolicy = new JSONObject("{\r\n" + "    \"types\": [\r\n" + "        {\r\n"
				+ "            \"name\": \"ImanFile\",\r\n" + "            \"properties\": [\r\n"
				+ "                {\r\n" + "                    \"name\": \"original_file_name\"\r\n"
				+ "                }\r\n" + ", {\r\n" + "                    \"name\": \"last_mod_date\"\r\n"
				+ "                }\r\n" + "            ]\r\n" + "        }\r\n" + "    ]\r\n" + "}");
		return TcConnection.callTeamcenterService(getContext(), Constants.OPERATION_GETFILEREADTICKETS,
				getFileReadTicketsJT, emptyPolicy, configurationName);
	}
	// END EXTRA CODE
}
