// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package tcconnector.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import tcconnector.foundation.TcConnection;
import tcconnector.internal.foundation.Constants;
import tcconnector.proxies.ExpandPSOneLevelResponse;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * SOA URL:
 * Cad-2007-01-StructureManagement/expandPSOneLevel
 * 
 * Description:
 * This actions finds the first level children of given parent bomline 
 * 
 * Returns:
 * An entity of type ExpandPSOneLevelResponse. Expanded child bomlines can be retrieved using association TcConnector.children. Partial errors can be retrieved using association TcConnector.ResponseData/TcConnector.PartialErrors.
 */
public class ExpandPSOneLevel extends UserAction<IMendixObject>
{
	/** @deprecated use inputEntity.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __inputEntity;
	private final tcconnector.proxies.ExpandPSOneLevelInput inputEntity;
	private final java.lang.String businessObjectMapping;
	private final java.lang.String ConfigurationName;
	private final java.lang.Boolean populateServiceDataObjects;

	public ExpandPSOneLevel(
		IContext context,
		IMendixObject _inputEntity,
		java.lang.String _businessObjectMapping,
		java.lang.String _configurationName,
		java.lang.Boolean _populateServiceDataObjects
	)
	{
		super(context);
		this.__inputEntity = _inputEntity;
		this.inputEntity = _inputEntity == null ? null : tcconnector.proxies.ExpandPSOneLevelInput.initialize(getContext(), _inputEntity);
		this.businessObjectMapping = _businessObjectMapping;
		this.ConfigurationName = _configurationName;
		this.populateServiceDataObjects = _populateServiceDataObjects;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		ExpandPSOneLevelResponse response = new ExpandPSOneLevelResponse(getContext());
		if(this.inputEntity != null) {
			response = (ExpandPSOneLevelResponse) TcConnection.callTeamcenterService(getContext(),
					Constants.OPERATION_EXPANDPSONELEVEL, inputEntity.getMendixObject(), response, SERVICE_OPERATION_MAP,
					businessObjectMapping, ConfigurationName, populateServiceDataObjects);
		}
		return response.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ExpandPSOneLevel";
	}

	// BEGIN EXTRA CODE
	private static final String SERVICE_OPERATION_MAP = "OperationMapping/Cad/2007-01/StructureManagement/ExpandPSOneLevel.json";
	// END EXTRA CODE
}
