// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package tcconnector.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import tcconnector.foundation.TcConnection;
import tcconnector.internal.foundation.Constants;
import tcconnector.proxies.GetWorkflowTemplatesResponse;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * SOA URL: 
 * Workflow-2008-06-Workflow/getWorkflowTemplates
 * 
 * Description:
 * Get the list of workflow templates given the list of target workspace objects and the All or Assigned criteria.
 * Returns:
 * An entity of type GetWorkflowTemplatesResponse. WorkflowTemplates can be retrieved using association TcConnector.workflowTemplates.Partial errors can be retrieved using association TcConnector.ResponseData/TcConnector.PartialErrors.
 */
public class GetWorkflowTemplates extends UserAction<IMendixObject>
{
	/** @deprecated use InputData.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __InputData;
	private final tcconnector.proxies.GetWorkflowTemplatesInput InputData;
	private final java.lang.String BusinessObjectMappings;
	private final java.lang.String ConfigurationName;

	public GetWorkflowTemplates(
		IContext context,
		IMendixObject _inputData,
		java.lang.String _businessObjectMappings,
		java.lang.String _configurationName
	)
	{
		super(context);
		this.__InputData = _inputData;
		this.InputData = _inputData == null ? null : tcconnector.proxies.GetWorkflowTemplatesInput.initialize(getContext(), _inputData);
		this.BusinessObjectMappings = _businessObjectMappings;
		this.ConfigurationName = _configurationName;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		GetWorkflowTemplatesResponse response = new GetWorkflowTemplatesResponse(getContext());
		response = (GetWorkflowTemplatesResponse) TcConnection.callTeamcenterService(getContext(),
				Constants.OPERATION_GETWORKFLOWTEMPLATES, InputData.getMendixObject(), response, SERVICE_OPERATION_MAP,
				BusinessObjectMappings, ConfigurationName, true);
		return response.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetWorkflowTemplates";
	}

	// BEGIN EXTRA CODE
	private static final String SERVICE_OPERATION_MAP = "OperationMapping/Workflow/2008-06/Workflow/getWorkflowTemplates.json";
	// END EXTRA CODE
}
