// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package tcconnector.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import tcconnector.foundation.TcConnection;
import tcconnector.internal.foundation.Constants;
import tcconnector.proxies.SearchResponse;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * SOA URL: 
 * Query-2014-11-Finder/performSearch
 * 
 * Description: 
 * This is a generic action to send the request to and receive the response from a the data provider. It routes search request to a specific provider specified as providerName in the searchInput, assuming the searchCriteria for the provider is represented in the searchCriteriaInput object e.g. 'Awp0SavedQuerySearchProvider' is provider that is used for general search. The input criteria for GeneralSearch is passed through the searchCriteriaInput object.
 * 
 * Returns:
 * An entity of type SearchResponse. Search Results can be retrieved using association TcConnector.searchResultsList. Partial errors can be retrieved using association TcConnector.ResponseData/TcConnector.PartialErrors.
 */
public class PerformSearch extends UserAction<IMendixObject>
{
	/** @deprecated use InputData.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __InputData;
	private final tcconnector.proxies.SearchInput InputData;
	private final java.lang.String BusinessObjectMappings;
	private final java.lang.String ConfigurationName;

	public PerformSearch(
		IContext context,
		IMendixObject _inputData,
		java.lang.String _businessObjectMappings,
		java.lang.String _configurationName
	)
	{
		super(context);
		this.__InputData = _inputData;
		this.InputData = _inputData == null ? null : tcconnector.proxies.SearchInput.initialize(getContext(), _inputData);
		this.BusinessObjectMappings = _businessObjectMappings;
		this.ConfigurationName = _configurationName;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		SearchResponse response = new SearchResponse(getContext());
		response = (SearchResponse) TcConnection.callTeamcenterService(getContext(), Constants.OPERATION_PERFORMSEARCH,
				InputData.getMendixObject(), response, SERVICE_OPERATION_MAP, BusinessObjectMappings,
				ConfigurationName, true);
		return response.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "PerformSearch";
	}

	// BEGIN EXTRA CODE
	private static final String SERVICE_OPERATION_MAP = "OperationMapping/Query/2014-11/Finder/performSearch.json";
	// END EXTRA CODE
}
