// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package tcconnector.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import tcconnector.foundation.TcConnection;
import tcconnector.internal.foundation.Constants;
import tcconnector.proxies.ServiceResponse;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * SOA URL:
 * Workflow-2012-10-Workflow/performAction2
 * 
 * Description:
 * This actions performs an action on a workflow task. The following actions are supported: 
 * Assign
 * Start
 * Complete
 * Skip
 * Suspend
 * Resume
 * Undo
 * Perform
 * Approve
 * Reject
 * Promote
 * Demote
 * Claim
 * 
 * Returns:
 * Partial errors can be retrieved using association TcConnector.ResponseData/TcConnector.PartialErrors.
 */
public class PerformAction extends UserAction<IMendixObject>
{
	/** @deprecated use InputData.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __InputData;
	private final tcconnector.proxies.PerformActionInput InputData;
	private final java.lang.String BusinessObjectMappings;
	private final java.lang.String ConfigurationName;

	public PerformAction(
		IContext context,
		IMendixObject _inputData,
		java.lang.String _businessObjectMappings,
		java.lang.String _configurationName
	)
	{
		super(context);
		this.__InputData = _inputData;
		this.InputData = _inputData == null ? null : tcconnector.proxies.PerformActionInput.initialize(getContext(), _inputData);
		this.BusinessObjectMappings = _businessObjectMappings;
		this.ConfigurationName = _configurationName;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		ServiceResponse response = new ServiceResponse(getContext());
		response = (ServiceResponse) TcConnection.callTeamcenterService(getContext(), Constants.OPERATION_PERFORMACTION,
				InputData.getMendixObject(), response, SERVICE_OPERATION_MAP, BusinessObjectMappings,
				ConfigurationName, true);
		return response.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "PerformAction";
	}

	// BEGIN EXTRA CODE
	private static final String SERVICE_OPERATION_MAP = "OperationMapping/Workflow/2012-10/Workflow/performAction2.json";
	// END EXTRA CODE
}
