// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package tcconnector.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import tcconnector.internal.servicehelper.AdvancedSearchHelper;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * SOA URL: 
 * Query-2010-04-SavedQuery/findSavedQueries
 * Query-2014-11-Finder/performSearch
 * 
 * Description: 
 * This is a specific action to send the request to and receive the response from a the data provider 'Awp0SavedQuerySearchProvider' for query 'Item - simple'. The input criteria for GeneralSearch query is passed through the generalQuerySearchInput object which is extended from .SearchInput Object.
 * 
 * Returns:
 * An entity of type SearchResponse. Search Results can be retrieved using association TcConnector.searchResultsList. Partial errors can be retrieved using association TcConnector.ResponseData/TcConnector.PartialErrors.
 * 
 * NOTE:
 * This action will work only if the teamcenter enviornment has active workspace installation .
 */
public class PerformItemSimpleQuerySearchAW extends UserAction<IMendixObject>
{
	/** @deprecated use itemSimpleQuerySearchInput.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __itemSimpleQuerySearchInput;
	private final tcconnector.proxies.SearchInput itemSimpleQuerySearchInput;
	private final java.lang.String businessObjectMapping;
	private final java.lang.String ConfigurationName;

	public PerformItemSimpleQuerySearchAW(
		IContext context,
		IMendixObject _itemSimpleQuerySearchInput,
		java.lang.String _businessObjectMapping,
		java.lang.String _configurationName
	)
	{
		super(context);
		this.__itemSimpleQuerySearchInput = _itemSimpleQuerySearchInput;
		this.itemSimpleQuerySearchInput = _itemSimpleQuerySearchInput == null ? null : tcconnector.proxies.SearchInput.initialize(getContext(), _itemSimpleQuerySearchInput);
		this.businessObjectMapping = _businessObjectMapping;
		this.ConfigurationName = _configurationName;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		return AdvancedSearchHelper.performAdvanceSearch(getContext(), KEY_ITEM_SIMPLE_QUERY_NAME,
				itemSimpleQuerySearchInput.getMendixObject(), businessObjectMapping, ConfigurationName);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "PerformItemSimpleQuerySearchAW";
	}

	// BEGIN EXTRA CODE
	private static final String KEY_ITEM_SIMPLE_QUERY_NAME = "Item - simple";
	// END EXTRA CODE
}
