// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package tcconnector.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import system.proxies.HttpHeader;
import tcconnector.foundation.exceptions.InvalidUserException;
import tcconnector.internal.foundation.Constants;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * This Java action retrieves cookies of an established session between Teamcenter and Mendix. User is expected to be logged in before this Java action is invoked.
 * Java action is expected to throw an error if there are no valid cookies. Application devloper is expected to handle the errors.
 */
public class RetrieveCookie extends UserAction<IMendixObject>
{
	/** @deprecated use Cookie.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Cookie;
	private final tcconnector.proxies.Cookie Cookie;

	public RetrieveCookie(
		IContext context,
		IMendixObject _cookie
	)
	{
		super(context);
		this.__Cookie = _cookie;
		this.Cookie = _cookie == null ? null : tcconnector.proxies.Cookie.initialize(getContext(), _cookie);
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		HttpHeader header = null;
		if (Cookie != null) {

			header = new HttpHeader(getContext());
			header.setKey("Cookie");
			header.setValue(Cookie.getName() + '=' + Cookie.getValue());
			header.commit();
		} else {
			throw new InvalidUserException(Constants.InvalidUserException);
		}
		return header.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "RetrieveCookie";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
