// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package teamcentertoolkit.actions;

import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import teamcentertoolkit.impl.Utils;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import static java.util.Objects.requireNonNull;
import com.mendix.systemwideinterfaces.core.UserAction;

public class JA_CreateDatasetSpecialization extends UserAction<IMendixObject>
{
	private final java.lang.String DatasetEntity;
	private final java.lang.String object_name;
	private final java.lang.String dataset_type;

	public JA_CreateDatasetSpecialization(
		IContext context,
		java.lang.String _datasetEntity,
		java.lang.String _object_name,
		java.lang.String _dataset_type
	)
	{
		super(context);
		this.DatasetEntity = _datasetEntity;
		this.object_name = _object_name;
		this.dataset_type = _dataset_type;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		validateInput();
		return createMyDataset();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_CreateDatasetSpecialization";
	}

	// BEGIN EXTRA CODE
	private void validateInput(){
		requireNonNull(object_name, "Dataset name cannot be empty");
		requireNonNull(dataset_type, "Dataset type cannot be empty");
	}
	
	private IMendixObject createMyDataset() throws CoreException {
		Utils.isSubClass(DatasetEntity, tcconnector.proxies.Dataset.entityName);
		IMendixObject myDatasetObject = Core.instantiate(getContext(), DatasetEntity);
		myDatasetObject.setValue(getContext(), "object_name", object_name);
		myDatasetObject.setValue(getContext(), "dataset_type", dataset_type);
		return myDatasetObject;
	}
	
	// END EXTRA CODE
}
