// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package teamcentertoolkit.actions;

import static java.util.Objects.requireNonNull;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import teamcentertoolkit.impl.CopyHelper;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Copies attributes from BaseCreateInput to ModelObject, where attributes are defined on both objects with the same type. Attributes that are not defined on ModelObject and attributes that are defined on both, but with a different attribute type, will be skipped.
 */
public class JA_CopyModelObjectToCreateInput extends UserAction<java.lang.Void>
{
	/** @deprecated use source.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __source;
	private final tcconnector.proxies.ModelObject source;
	/** @deprecated use target.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __target;
	private final tcconnector.proxies.BaseCreateInput target;

	public JA_CopyModelObjectToCreateInput(
		IContext context,
		IMendixObject _source,
		IMendixObject _target
	)
	{
		super(context);
		this.__source = _source;
		this.source = _source == null ? null : tcconnector.proxies.ModelObject.initialize(getContext(), _source);
		this.__target = _target;
		this.target = _target == null ? null : tcconnector.proxies.BaseCreateInput.initialize(getContext(), _target);
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		requireNonNull(source, "Source is required.");
		requireNonNull(target, "Target is required.");

		new CopyHelper(source.getMendixObject(), getContext()).copy(target.getMendixObject());
		
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_CopyModelObjectToCreateInput";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
