// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package teamcentertoolkit.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import teamcentertoolkit.impl.CastHelper;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import static java.util.Objects.requireNonNull;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Casts a TcConnector.ModelObject
 */
public class JA_ModelObjectList_Cast extends UserAction<java.util.List<IMendixObject>>
{
	/** @deprecated use com.mendix.utils.ListUtils.map(inputModelObjectList, com.mendix.systemwideinterfaces.core.IEntityProxy::getMendixObject) instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final java.util.List<IMendixObject> __inputModelObjectList;
	private final java.util.List<tcconnector.proxies.ModelObject> inputModelObjectList;
	private final java.lang.String modelObjectType;
	private final java.lang.Boolean raiseError;

	public JA_ModelObjectList_Cast(
		IContext context,
		java.util.List<IMendixObject> _inputModelObjectList,
		java.lang.String _modelObjectType,
		java.lang.Boolean _raiseError
	)
	{
		super(context);
		this.__inputModelObjectList = _inputModelObjectList;
		this.inputModelObjectList = java.util.Optional.ofNullable(_inputModelObjectList)
			.orElse(java.util.Collections.emptyList())
			.stream()
			.map(inputModelObjectListElement -> tcconnector.proxies.ModelObject.initialize(getContext(), inputModelObjectListElement))
			.collect(java.util.stream.Collectors.toList());
		this.modelObjectType = _modelObjectType;
		this.raiseError = _raiseError;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		requireNonNull(inputModelObjectList, "InputModelObjectList is required");
		requireNonNull(modelObjectType, "ModelObjectType is required.");

		return new CastHelper(modelObjectType, raiseError).cast(inputModelObjectList);			
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_ModelObjectList_Cast";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
