// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package teamcentertoolkit.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import teamcentertoolkit.impl.CastHelper;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import static java.util.Objects.requireNonNull;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Casts a TcConnector.ModelObject
 */
public class JA_ModelObject_Cast extends UserAction<IMendixObject>
{
	/** @deprecated use inputModelObject.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __inputModelObject;
	private final tcconnector.proxies.ModelObject inputModelObject;
	private final java.lang.String modelObjectType;
	private final java.lang.Boolean raiseError;

	public JA_ModelObject_Cast(
		IContext context,
		IMendixObject _inputModelObject,
		java.lang.String _modelObjectType,
		java.lang.Boolean _raiseError
	)
	{
		super(context);
		this.__inputModelObject = _inputModelObject;
		this.inputModelObject = _inputModelObject == null ? null : tcconnector.proxies.ModelObject.initialize(getContext(), _inputModelObject);
		this.modelObjectType = _modelObjectType;
		this.raiseError = _raiseError;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		requireNonNull(inputModelObject, "InputModelObject is required.");
		requireNonNull(modelObjectType, "ModelObjectType is required.");

		return new CastHelper(modelObjectType, raiseError).cast(inputModelObject);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_ModelObject_Cast";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
